import { ApiProperty } from '@nestjs/swagger';

export class RefreshResponse {
  @ApiProperty({
    example:
      'eyJhbGciOiJIUzI1NiIsImtpZCI6Ik5mci90WmU2WTdIN0J6STAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL21kbXdkdmFvYWlsamZyaW9teXFyLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwMjA1MTdkMy0wNGM0LTQ1YzMtOTU3OC0yMDMyODlmYjc1ZGIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ3MDE3ODQyLCJpYXQiOjE3NDcwMTQyNDIsImVtYWlsIjoiZWFydGt1YWQ1QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJlYXJ0a3VhZDVAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiMDIwNTE3ZDMtMDRjNC00NWMzLTk1NzgtMjAzMjg5ZmI3NWRiIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDcwMTQwMzZ9XSwic2Vzc2lvbl9pZCI6IjVkNTRiMDdlLWUzMTktNGVjMS1iNjQ2LTFlZjYxOThjY2Y1OSIsImlzX2Fub255bW91cyI6ZmFsc2V9.aKh8_im7HJGcKE0Z4zEZ1GCuOdiBkJMKAwCByTsdBqQ',
  })
  accessToken: string;
}
